/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateCharacterRouteImport } from './routes/create-character'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMissionsRouteImport } from './routes/_app.missions'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCharacterRouteImport } from './routes/_app.character'
import { Route as AppBattleRouteImport } from './routes/_app.battle'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCharacterRoute = CreateCharacterRouteImport.update({
  id: '/create-character',
  path: '/create-character',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCharacterRoute = AppCharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => AppRoute,
} as any)
const AppBattleRoute = AppBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-character': typeof CreateCharacterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/battle': typeof AppBattleRoute
  '/character': typeof AppCharacterRoute
  '/dashboard': typeof AppDashboardRoute
  '/missions': typeof AppMissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-character': typeof CreateCharacterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/battle': typeof AppBattleRoute
  '/character': typeof AppCharacterRoute
  '/dashboard': typeof AppDashboardRoute
  '/missions': typeof AppMissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/create-character': typeof CreateCharacterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/battle': typeof AppBattleRoute
  '/_app/character': typeof AppCharacterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/missions': typeof AppMissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-character'
    | '/login'
    | '/register'
    | '/battle'
    | '/character'
    | '/dashboard'
    | '/missions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-character'
    | '/login'
    | '/register'
    | '/battle'
    | '/character'
    | '/dashboard'
    | '/missions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/create-character'
    | '/login'
    | '/register'
    | '/_app/battle'
    | '/_app/character'
    | '/_app/dashboard'
    | '/_app/missions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CreateCharacterRoute: typeof CreateCharacterRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-character': {
      id: '/create-character'
      path: '/create-character'
      fullPath: '/create-character'
      preLoaderRoute: typeof CreateCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/missions': {
      id: '/_app/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/character': {
      id: '/_app/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof AppCharacterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/battle': {
      id: '/_app/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof AppBattleRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBattleRoute: typeof AppBattleRoute
  AppCharacterRoute: typeof AppCharacterRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMissionsRoute: typeof AppMissionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBattleRoute: AppBattleRoute,
  AppCharacterRoute: AppCharacterRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMissionsRoute: AppMissionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CreateCharacterRoute: CreateCharacterRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
