/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateCharacterRouteImport } from './routes/create-character'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCharactersRouteImport } from './routes/admin.characters'
import { Route as AppShopRouteImport } from './routes/_app.shop'
import { Route as AppRankingRouteImport } from './routes/_app.ranking'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMissionsRouteImport } from './routes/_app.missions'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppJutsusRouteImport } from './routes/_app.jutsus'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClanRouteImport } from './routes/_app.clan'
import { Route as AppCharacterRouteImport } from './routes/_app.character'
import { Route as AppBattleRouteImport } from './routes/_app.battle'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCharacterRoute = CreateCharacterRouteImport.update({
  id: '/create-character',
  path: '/create-character',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCharactersRoute = AdminCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AdminRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppJutsusRoute = AppJutsusRouteImport.update({
  id: '/jutsus',
  path: '/jutsus',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClanRoute = AppClanRouteImport.update({
  id: '/clan',
  path: '/clan',
  getParentRoute: () => AppRoute,
} as any)
const AppCharacterRoute = AppCharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => AppRoute,
} as any)
const AppBattleRoute = AppBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/create-character': typeof CreateCharacterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/battle': typeof AppBattleRoute
  '/character': typeof AppCharacterRoute
  '/clan': typeof AppClanRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/jutsus': typeof AppJutsusRoute
  '/map': typeof AppMapRoute
  '/missions': typeof AppMissionsRoute
  '/profile': typeof AppProfileRoute
  '/ranking': typeof AppRankingRoute
  '/shop': typeof AppShopRoute
  '/admin/characters': typeof AdminCharactersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-character': typeof CreateCharacterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/battle': typeof AppBattleRoute
  '/character': typeof AppCharacterRoute
  '/clan': typeof AppClanRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/jutsus': typeof AppJutsusRoute
  '/map': typeof AppMapRoute
  '/missions': typeof AppMissionsRoute
  '/profile': typeof AppProfileRoute
  '/ranking': typeof AppRankingRoute
  '/shop': typeof AppShopRoute
  '/admin/characters': typeof AdminCharactersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/create-character': typeof CreateCharacterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/battle': typeof AppBattleRoute
  '/_app/character': typeof AppCharacterRoute
  '/_app/clan': typeof AppClanRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/jutsus': typeof AppJutsusRoute
  '/_app/map': typeof AppMapRoute
  '/_app/missions': typeof AppMissionsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/shop': typeof AppShopRoute
  '/admin/characters': typeof AdminCharactersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/create-character'
    | '/login'
    | '/register'
    | '/battle'
    | '/character'
    | '/clan'
    | '/dashboard'
    | '/inventory'
    | '/jutsus'
    | '/map'
    | '/missions'
    | '/profile'
    | '/ranking'
    | '/shop'
    | '/admin/characters'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-character'
    | '/login'
    | '/register'
    | '/battle'
    | '/character'
    | '/clan'
    | '/dashboard'
    | '/inventory'
    | '/jutsus'
    | '/map'
    | '/missions'
    | '/profile'
    | '/ranking'
    | '/shop'
    | '/admin/characters'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/create-character'
    | '/login'
    | '/register'
    | '/_app/battle'
    | '/_app/character'
    | '/_app/clan'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/jutsus'
    | '/_app/map'
    | '/_app/missions'
    | '/_app/profile'
    | '/_app/ranking'
    | '/_app/shop'
    | '/admin/characters'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CreateCharacterRoute: typeof CreateCharacterRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-character': {
      id: '/create-character'
      path: '/create-character'
      fullPath: '/create-character'
      preLoaderRoute: typeof CreateCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/characters': {
      id: '/admin/characters'
      path: '/characters'
      fullPath: '/admin/characters'
      preLoaderRoute: typeof AdminCharactersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions': {
      id: '/_app/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jutsus': {
      id: '/_app/jutsus'
      path: '/jutsus'
      fullPath: '/jutsus'
      preLoaderRoute: typeof AppJutsusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clan': {
      id: '/_app/clan'
      path: '/clan'
      fullPath: '/clan'
      preLoaderRoute: typeof AppClanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/character': {
      id: '/_app/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof AppCharacterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/battle': {
      id: '/_app/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof AppBattleRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBattleRoute: typeof AppBattleRoute
  AppCharacterRoute: typeof AppCharacterRoute
  AppClanRoute: typeof AppClanRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppJutsusRoute: typeof AppJutsusRoute
  AppMapRoute: typeof AppMapRoute
  AppMissionsRoute: typeof AppMissionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRankingRoute: typeof AppRankingRoute
  AppShopRoute: typeof AppShopRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBattleRoute: AppBattleRoute,
  AppCharacterRoute: AppCharacterRoute,
  AppClanRoute: AppClanRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppJutsusRoute: AppJutsusRoute,
  AppMapRoute: AppMapRoute,
  AppMissionsRoute: AppMissionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRankingRoute: AppRankingRoute,
  AppShopRoute: AppShopRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminCharactersRoute: typeof AdminCharactersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCharactersRoute: AdminCharactersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CreateCharacterRoute: CreateCharacterRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
